<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSZR0xUL\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSZR0xUL/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerSZR0xUL.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerSZR0xUL\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerSZR0xUL\App_KernelProdContainer([
    'container.build_hash' => 'SZR0xUL',
    'container.build_id' => 'cc016818',
    'container.build_time' => 1677161027,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSZR0xUL');
