<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJOEddiA\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJOEddiA/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJOEddiA.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJOEddiA\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJOEddiA\App_KernelDevDebugContainer([
    'container.build_hash' => 'JOEddiA',
    'container.build_id' => 'f11cec4f',
    'container.build_time' => 1677230312,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJOEddiA');
